### ISSUE TITLE
 'edgemap' missing from 'hr_utils'

### ISSUE THREAD

**Issue by zicongzhou818** [clatfd/GNN-ART-LABEL#7]
Hi, thank you for the excellent work! I am very interested and learning your work. As I walked though ArtLabel.ipynb and tried the Hierarchical Refinement part, this was reported：

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_21804\3478960230.py in <module>
----> 1 from hr_utils import nodeconnection, matchvestype, nodedist, edgemap
      2 
      3 branch_dist_mean = {}
      4 branch_dist_std = {}
      5 branchdists = [[] for i in range(VESTYPENUM)]

ImportError: cannot import name 'edgemap' from 'hr_utils'

Would you please update the hr_utils.py with the module edgemap in it? Thank you!

**Comment by clatfd** [comment]
Thanks for your interest! 
Sorry, edgemap was defined in hr_utils but later on I moved that to the "refinement using HR" section. Thanks for pointing that out. I have added that in "collect ves branch length" as well.

**Comment by zicongzhou818** [comment]
Thanks for the update. The issue seems has been resolved. But, I encountered another issue in section "check and display HR results". Do you want me to close this one then open a new one or you don't mind clarify that here?

**Comment by clatfd** [comment]
If your issue is not related with this topic, please create a new issue.
